/* projeteuler.net : PROBLEM 2 ::Even Fibonacci numbers
	 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
   
#include <iostream>
using namespace std;

void f()
{
	int x1=1;
	int x2=2;
	int sum=0;
	while(x2<=40000000)
	{
		if(x1%2==0)
		{sum+=x1;
		}
		if(x2%2==0)
		{sum+=x2;
		}
		x1+=x2;
		x2+=x1;
	}	
	cout<<"the sum of this fibonnachi seq is:"<<sum;
}

int main()
{
    f();
    return 0;
}
